flasher:
  presets:
    created:
      type: success
      title: Notificaci贸n
      message: Elemento creado satisfactoriamente
    updated:
      type: success
      title: Notificaci贸n
      message: Elemento modificado satisfactoriamente
    saved:
      type: success
      title: Notificaci贸n
      message: Elemento guardado satisfactoriamente
    deleted:
      type: success
      title: Notificaci贸n
      message: Elemento eliminado satisfactoriamente