# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.calendar_suscriber:
        class: App\EventSubscriber\CalendarSubscriber
        tags:
            - { name: kernel.event_subscriber }

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%uploads_directory%'

    App\Service\BotTelegram:
#        arguments:
#            $token: '5485647380:AAGk5WVV1xAa6x141NmCyXyof9GPn_Gz-Dg'
#            $urlstart: 'https://api.telegram.org/bot'
#            $urlend: '/sendMessage'
#            $chatid: '-495076220'

#    App\Service\ActiveDirectoryService:
#        arguments:
#            $connection_string: 'ldaps://192.168.176.128:636'
#            $bind_dn: 'OU=NTV,DC=domain,DC=test,DC=com'
#            $domain_fqdn: 'Corporativa'
#            $bind_user: 'CN=LDAP Search,CN=Users,DC=domain,DC=test,DC=com'
#            $bind_password: 'TGQ0cFMzNHJjaDIwMjIq'

    App\Security\ActiveDirectoryService:
      arguments:
        $connection_string: 'ldaps://10.3.5.3:636'
        $bind_dn: 'OU=Usuarios,DC=ntv,DC=icrt,DC=cu'
        $domain_fqdn: 'Corporativa'
        $bind_user: 'CN=LDAP Search,CN=Users,DC=ntv,DC=icrt,DC=cu'
        $bind_password: 'QWRtKkxkYXA0NTY='


    App\Security\ActiveDirectoryUserService:
        parent: App\Security\ActiveDirectoryService

